language: node_js
node_js:
- '0.12'

env:
  global:
  - MY_VAR=DefinedInGlobal
  - DYN_VAR=Dynamic

before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && DYN_VAR="Overriden" || true'

script:
- node build.js